name: sby Formal Verification
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest sby sources
        uses: actions/checkout@v3
        with:
          repository: YosysHQ/sby
      - name: Setup test environment
        uses: YosysHQ/setup-oss-cad-suite@v1
        
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: llvm

      - run: |
          ghdl --version
          $GHDL --version
      - name: formal verification
        run: |
          cd cocotb_sim/ && sby --yosys "yosys -m ghdl" -f uart.sby
          
      - name: check results
        run: |
          cd cocotb_sim/ && var=$(cat uart_task_bmc/uart_task_bmc.xml | grep -o -E 'failures.{0,3}' | head -1 | cut -f2- -d\") 
          if [ $var = 0 ]; then exit 0; else exit 1; fi
